DROP TABLE LIKEDREVIEW;
DROP TABLE REVIEW;

DROP TABLE RESERVATION;
DROP TABLE COUPON;
DROP TABLE RATE;

DROP TABLE USER_FAVORITEVILLA;

DROP TABLE VILLA_FEATURE;
DROP TABLE FEATURES;
DROP TABLE VILLA;

DROP TABLE OWNER;
DROP TABLE MANAGER;
DROP TABLE USERS;

COMMIT;
