SELECT VILLA.VILLA_ID, NAME FROM FEATURES, VILLA_FEATURE, VILLA
	WHERE FEATURE_NAME='Jacuzzi'
		AND VILLA.VILLA_ID=VILLA_FEATURE.VILLA_ID
		AND VILLA_FEATURE.FEATURE_ID=FEATURES.FEATURE_ID
MINUS
SELECT VILLA.VILLA_ID, NAME FROM FEATURES, VILLA_FEATURE, VILLA
	WHERE FEATURE_NAME='pets allowed'
		AND VILLA.VILLA_ID=VILLA_FEATURE.VILLA_ID
		AND VILLA_FEATURE.FEATURE_ID=FEATURES.FEATURE_ID;
