SELECT USERS.ID, USERS.FIRST_NAME, USERS.LAST_NAME
  FROM RESERVATION RA, RESERVATION RB, USERS
  WHERE RA.USER_ID=RB.USER_ID
    AND RA.RESERVATION_ID!=RB.RESERVATION_ID
    AND (
          (RA.END_DATE>RB.START_DATE AND RA.END_DATE<=RB.END_DATE)
          OR
          (RA.START_DATE>=RB.START_DATE AND RA.START_DATE<RB.END_DATE)
        )
    AND RA.VILLA_ID!=RB.VILLA_ID
    AND USERS.ID=RA.USER_ID
  GROUP BY USERS.ID, USERS.FIRST_NAME, USERS.LAST_NAME;
