SELECT FIRST_NAME, LAST_NAME, SUM(DEPOSIT) FROM USERS, RESERVATION
    WHERE USERS.ID=RESERVATION.USER_ID
      AND RESERVATION.START_DATE>=TO_DATE('2013/01/01', 'yyyy/mm/dd')
      AND RESERVATION.END_DATE<TO_DATE('2014/01/01', 'yyyy/mm/dd')
    GROUP BY RESERVATION.USER_ID, FIRST_NAME, LAST_NAME
    HAVING SUM(DEPOSIT) >=
                        (SELECT MIN(INDIVIDUALSUM) AS FLOOR FROM
                          (SELECT SUM(DEPOSIT) AS INDIVIDUALSUM FROM RESERVATION
                            WHERE RESERVATION.START_DATE>=TO_DATE('2013/01/01', 'yyyy/mm/dd')
                              AND RESERVATION.END_DATE<TO_DATE('2014/01/01', 'yyyy/mm/dd')
                            GROUP BY RESERVATION.USER_ID
                            ORDER BY SUM(DEPOSIT) DESC)
                          WHERE ROWNUM <= 3)
    ORDER BY SUM(DEPOSIT) DESC;
