SELECT AVG(floor(months_between(RESERVATION.START_DATE, USERS.DOB) /12)) AS "AVERAGE AGE" FROM USERS, RESERVATION
  WHERE USERS.ID=RESERVATION.USER_ID
    AND ((RESERVATION.START_DATE>=TO_DATE('2013/09/01', 'yyyy/mm/dd')
            AND RESERVATION.START_DATE<TO_DATE('2014/01/01', 'yyyy/mm/dd'))
          OR
          (RESERVATION.END_DATE>TO_DATE('2013/09/01', 'yyyy/mm/dd')
            AND RESERVATION.END_DATE<=TO_DATE('2014/01/01', 'yyyy/mm/dd'))
          );
