SELECT VILLA.VILLA_ID, VILLA.NAME, USERS.ID, USERS.FIRST_NAME, USERS.LAST_NAME
  FROM USERS, VILLA,
        (SELECT VILLA_ID AS VILLA_ID FROM 
            (SELECT V.VILLA_ID, V.NAME, AVG(REVIEW.RATING) AS AVERAGE
              FROM VILLA V, REVIEW
              WHERE V.VILLA_ID=REVIEW.VILLA_ID
              GROUP BY V.VILLA_ID, V.NAME
              ORDER BY AVG(REVIEW.RATING) DESC)
            WHERE ROWNUM <= 3) HIGHTHREE
  WHERE USERS.ID=VILLA.OWNER
    AND VILLA.VILLA_ID=HIGHTHREE.VILLA_ID;
