SELECT REVIEWER, USERS.FIRST_NAME, USERS.LAST_NAME
  FROM USERS,
       (SELECT REVIEWER, COUNT(R1.REVIEWER) AS REVIEWER_TOPNUMBER
          FROM 
            (SELECT R.VILLA_ID, COUNT(R.VILLA_ID) AS NLIKES, R.USER_ID AS REVIEWER
              FROM REVIEW R, LIKEDREVIEW LR
              WHERE R.REVIEW_ID=LR.REVIEW_ID
              GROUP BY R.REVIEW_ID, R.VILLA_ID, R.USER_ID) R1
          WHERE R1.NLIKES>=
            (SELECT MAX(COUNT(R.VILLA_ID))
              FROM REVIEW R, LIKEDREVIEW LR
              WHERE R.REVIEW_ID=LR.REVIEW_ID
                AND R.VILLA_ID=R1.VILLA_ID
              GROUP BY R.REVIEW_ID, R.VILLA_ID)
          GROUP BY R1.REVIEWER),
       (SELECT MAX(COUNT(R1.REVIEWER)) AS TOPREVIEWER_TOPNUMBER
          FROM 
            (SELECT R.VILLA_ID, COUNT(R.VILLA_ID) AS NLIKES, R.USER_ID AS REVIEWER
              FROM REVIEW R, LIKEDREVIEW LR
              WHERE R.REVIEW_ID=LR.REVIEW_ID
              GROUP BY R.REVIEW_ID, R.VILLA_ID, R.USER_ID) R1
          WHERE R1.NLIKES>=
            (SELECT MAX(COUNT(R.VILLA_ID))
              FROM REVIEW R, LIKEDREVIEW LR
              WHERE R.REVIEW_ID=LR.REVIEW_ID
                AND R.VILLA_ID=R1.VILLA_ID
              GROUP BY R.REVIEW_ID, R.VILLA_ID)
          GROUP BY R1.REVIEWER)
  WHERE USERS.ID=REVIEWER AND REVIEWER_TOPNUMBER>=TOPREVIEWER_TOPNUMBER;


-- -- Higher performance version: (but not considering ties)
-- SELECT REVIEWER, FIRST_NAME, LAST_NAME
--   FROM USERS, 
--       (SELECT REVIEWER
--           FROM (SELECT REVIEWER, COUNT(REVIEWER)
--                   FROM (SELECT R.VILLA_ID, COUNT(R.VILLA_ID) AS NLIKES, R.USER_ID AS REVIEWER
--                               ,ROW_NUMBER() OVER (PARTITION BY R.VILLA_ID ORDER BY COUNT(R.VILLA_ID) DESC) AS RN
--                           FROM REVIEW R, LIKEDREVIEW LR
--                           WHERE R.REVIEW_ID=LR.REVIEW_ID
--                           GROUP BY R.REVIEW_ID, R.VILLA_ID, R.USER_ID)
--                   WHERE RN=1
--                   GROUP BY REVIEWER
--                   ORDER BY COUNT(REVIEWER) DESC)
--           WHERE ROWNUM=1) TOPREVIEWER
--   WHERE TOPREVIEWER.REVIEWER=USERS.ID;
