SELECT OWNER, 1 - OCCUPYCOUNTER2 / ALLCOUNTER
  FROM (SELECT ALLCOUNTER,
            CASE WHEN OCCUPYCOUNTER is NULL THEN 0 ELSE OCCUPYCOUNTER END AS OCCUPYCOUNTER2,
            COUNTTABLE.OWNER
          FROM (SELECT VILLA.OWNER, COUNT(VILLA.OWNER) ALLCOUNTER
                  FROM VILLA
                  GROUP BY VILLA.OWNER) COUNTTABLE
                LEFT OUTER JOIN
                (SELECT VILLA.OWNER, COUNT(VILLA.OWNER) AS OCCUPYCOUNTER
                    FROM RESERVATION, VILLA
                    WHERE RESERVATION.START_DATE<=TO_DATE('2014/08/15', 'yyyy/mm/dd')
                      AND RESERVATION.END_DATE>TO_DATE('2014/08/15', 'yyyy/mm/dd')
                      AND RESERVATION.VILLA_ID=VILLA.VILLA_ID
                    GROUP BY RESERVATION.VILLA_ID, VILLA.OWNER) OCCUPYTABLE
                ON COUNTTABLE.OWNER = OCCUPYTABLE.OWNER);
